/* DEFINIÇÃO DOS PACKS DE ICONS */

let defaultPack = [
    "imagens/iconPacks/default/001-3d glasses.png",
    "imagens/iconPacks/default/002-toy machine.png",
    "imagens/iconPacks/default/003-calculator.png",
    "imagens/iconPacks/default/004-cassette.png",
    "imagens/iconPacks/default/005-computer.png",
    "imagens/iconPacks/default/006-computer.png",
    "imagens/iconPacks/default/007-disk.png",
    "imagens/iconPacks/default/008-toy.png",
    "imagens/iconPacks/default/009-game console.png",
    "imagens/iconPacks/default/010-game console.png",
    "imagens/iconPacks/default/011-game console.png",
    "imagens/iconPacks/default/012-game console.png",
    "imagens/iconPacks/default/013-glasses.png",
    "imagens/iconPacks/default/014-joystick.png",
    "imagens/iconPacks/default/015-joystick.png",
    "imagens/iconPacks/default/016-joystick.png",
    "imagens/iconPacks/default/017-lightsaber.png",
    "imagens/iconPacks/default/018-mac.png",
    "imagens/iconPacks/default/019-computer.png",
    "imagens/iconPacks/default/020-mouse.png",
    "imagens/iconPacks/default/021-picture.png",
    "imagens/iconPacks/default/022-headphones.png",
    "imagens/iconPacks/default/023-recorder.png",
    "imagens/iconPacks/default/024-voice recorder.png",
    "imagens/iconPacks/default/025-stereo.png",
    "imagens/iconPacks/default/026-toy.png",
    "imagens/iconPacks/default/027-tv.png",
    "imagens/iconPacks/default/028-tv.png",
    "imagens/iconPacks/default/029-tv.png",
    "imagens/iconPacks/default/030-video player.png",
    "imagens/iconPacks/default/031-video tape.png",
    "imagens/iconPacks/default/032-view.png",
    "imagens/iconPacks/default/033-calculator.png",
    "imagens/iconPacks/default/034-watch.png"]

let foodPack = [
    "imagens/iconPacks/food/1.png",
    "imagens/iconPacks/food/2.png",
    "imagens/iconPacks/food/3.png",
    "imagens/iconPacks/food/4.png",
    "imagens/iconPacks/food/5.png",
    "imagens/iconPacks/food/6.png",
    "imagens/iconPacks/food/7.png",
    "imagens/iconPacks/food/8.png",
    "imagens/iconPacks/food/9.png",
    "imagens/iconPacks/food/10.png",
    "imagens/iconPacks/food/11.png",
    "imagens/iconPacks/food/12.png",
    "imagens/iconPacks/food/13.png",
    "imagens/iconPacks/food/14.png",
    "imagens/iconPacks/food/15.png",
    "imagens/iconPacks/food/16.png",
    "imagens/iconPacks/food/17.png",
    "imagens/iconPacks/food/18.png",
    "imagens/iconPacks/food/19.png",
    "imagens/iconPacks/food/20.png"]

let desertPack = ["imagens/iconPacks/desert/001-cactus.png",
"imagens/iconPacks/desert/002-pyramid.png",
"imagens/iconPacks/desert/003-road.png",
"imagens/iconPacks/desert/004-sphinx.png",
"imagens/iconPacks/desert/005-palm tree.png",
"imagens/iconPacks/desert/006-oil barrel.png",
"imagens/iconPacks/desert/007-oasis.png",
"imagens/iconPacks/desert/008-hot.png",
"imagens/iconPacks/desert/009-desert.png",
"imagens/iconPacks/desert/010-canteen.png",
"imagens/iconPacks/desert/011-tornado.png",
"imagens/iconPacks/desert/012-dune.png",
"imagens/iconPacks/desert/013-compass.png",
"imagens/iconPacks/desert/014-ruins.png",
"imagens/iconPacks/desert/015-well.png",
"imagens/iconPacks/desert/016-thermometer.png",
"imagens/iconPacks/desert/017-cart.png",
"imagens/iconPacks/desert/018-cobra.png",
"imagens/iconPacks/desert/019-wagon.png",
"imagens/iconPacks/desert/020-pick.png",
"imagens/iconPacks/desert/021-camel.png",
"imagens/iconPacks/desert/022-bedouin.png",
"imagens/iconPacks/desert/023-eagle.png",
"imagens/iconPacks/desert/024-bedouin.png",
"imagens/iconPacks/desert/025-scorpion.png",
"imagens/iconPacks/desert/026-mosque.png",
"imagens/iconPacks/desert/027-mountain.png",
"imagens/iconPacks/desert/028-turtle.png",
"imagens/iconPacks/desert/029-canyon.png",
"imagens/iconPacks/desert/030-mine.png",
"imagens/iconPacks/desert/031-building.png",
"imagens/iconPacks/desert/032-tent.png",
"imagens/iconPacks/desert/033-skull.png",
"imagens/iconPacks/desert/034-sword.png",
"imagens/iconPacks/desert/035-skull.png",
"imagens/iconPacks/desert/036-map.png",
"imagens/iconPacks/desert/037-location.png",
"imagens/iconPacks/desert/038-drought.png",
"imagens/iconPacks/desert/039-cave.png",
"imagens/iconPacks/desert/040-hat.png",
"imagens/iconPacks/desert/041-amphora.png",
"imagens/iconPacks/desert/042-oil derrick.png",
"imagens/iconPacks/desert/043-sandstorm.png",
"imagens/iconPacks/desert/044-petroleum.png",
"imagens/iconPacks/desert/045-signpost.png",
"imagens/iconPacks/desert/046-hat.png",
"imagens/iconPacks/desert/047-dead tree.png",
"imagens/iconPacks/desert/048-rug.png",
"imagens/iconPacks/desert/049-water tank.png",
"imagens/iconPacks/desert/050-oil lamp.png"]

let emojiPack = ["imagens/iconPacks/emoji/001-smile-7.png",
"imagens/iconPacks/emoji/002-smile-8.png",
"imagens/iconPacks/emoji/003-smile-9.png",
"imagens/iconPacks/emoji/004-smile-10.png",
"imagens/iconPacks/emoji/005-smile-11.png",
"imagens/iconPacks/emoji/006-smile-12.png",
"imagens/iconPacks/emoji/007-smile-13.png",
"imagens/iconPacks/emoji/008-smile-14.png",
"imagens/iconPacks/emoji/009-smile-15.png",
"imagens/iconPacks/emoji/010-smile-16.png",
"imagens/iconPacks/emoji/011-smile-17.png",
"imagens/iconPacks/emoji/012-smile-18.png",
"imagens/iconPacks/emoji/013-smile-19.png",
"imagens/iconPacks/emoji/014-smile.png",
"imagens/iconPacks/emoji/015-smile-1.png",
"imagens/iconPacks/emoji/016-smile-2.png",
"imagens/iconPacks/emoji/017-smile-3.png",
"imagens/iconPacks/emoji/018-smile-4.png",
"imagens/iconPacks/emoji/019-smile-5.png",
"imagens/iconPacks/emoji/020-smile-6.png"]

let epidemicPack = ["imagens/iconPacks/epidemic/001-bacteria-2.png",
"imagens/iconPacks/epidemic/002-spread.png",
"imagens/iconPacks/epidemic/003-bacteria-3.png",
"imagens/iconPacks/epidemic/004-bacteria-4.png",
"imagens/iconPacks/epidemic/005-sign.png",
"imagens/iconPacks/epidemic/006-man.png",
"imagens/iconPacks/epidemic/007-bacteria-6.png",
"imagens/iconPacks/epidemic/008-bacteria-5.png",
"imagens/iconPacks/epidemic/009-eye.png",
"imagens/iconPacks/epidemic/010-man-1.png",
"imagens/iconPacks/epidemic/011-bacteria-7.png",
"imagens/iconPacks/epidemic/012-bacteria-8.png",
"imagens/iconPacks/epidemic/013-bacteria-9.png",
"imagens/iconPacks/epidemic/014-bacteria-10.png",
"imagens/iconPacks/epidemic/015-thermometer.png",
"imagens/iconPacks/epidemic/016-drop-1.png",
"imagens/iconPacks/epidemic/017-bacteria.png",
"imagens/iconPacks/epidemic/018-drop.png",
"imagens/iconPacks/epidemic/019-drop-2.png",
"imagens/iconPacks/epidemic/020-bacteria-1.png"]

let legoPack = ["imagens/iconPacks/lego/001-lego.png",
"imagens/iconPacks/lego/002-lego.png",
"imagens/iconPacks/lego/003-lego.png",
"imagens/iconPacks/lego/004-lego.png",
"imagens/iconPacks/lego/005-lego.png",
"imagens/iconPacks/lego/006-lego.png",
"imagens/iconPacks/lego/007-lego.png",
"imagens/iconPacks/lego/008-lego.png",
"imagens/iconPacks/lego/009-lego.png",
"imagens/iconPacks/lego/010-lego.png",
"imagens/iconPacks/lego/011-lego.png",
"imagens/iconPacks/lego/012-lego.png",
"imagens/iconPacks/lego/013-lego.png",
"imagens/iconPacks/lego/014-lego.png",
"imagens/iconPacks/lego/015-lego.png",
"imagens/iconPacks/lego/016-lego.png",
"imagens/iconPacks/lego/017-lego.png",
"imagens/iconPacks/lego/018-lego.png",
"imagens/iconPacks/lego/019-lego.png",
"imagens/iconPacks/lego/020-lego.png",
"imagens/iconPacks/lego/021-lego.png",
"imagens/iconPacks/lego/022-lego.png",
"imagens/iconPacks/lego/023-lego.png",
"imagens/iconPacks/lego/024-lego.png",
"imagens/iconPacks/lego/025-lego.png",
"imagens/iconPacks/lego/026-ninja.png",
"imagens/iconPacks/lego/027-cowboy.png",
"imagens/iconPacks/lego/028-knight.png",
"imagens/iconPacks/lego/029-explorer.png",
"imagens/iconPacks/lego/030-scuba diver.png",
"imagens/iconPacks/lego/031-clown.png",
"imagens/iconPacks/lego/032-boy.png",
"imagens/iconPacks/lego/033-native american.png",
"imagens/iconPacks/lego/034-cashier.png",
"imagens/iconPacks/lego/035-spy.png",
"imagens/iconPacks/lego/036-mariachi.png",
"imagens/iconPacks/lego/037-pirate.png",
"imagens/iconPacks/lego/038-fisherman.png",
"imagens/iconPacks/lego/039-cyborg.png",
"imagens/iconPacks/lego/040-vampire.png",
"imagens/iconPacks/lego/041-businessman.png",
"imagens/iconPacks/lego/042-conquistador.png",
"imagens/iconPacks/lego/043-DJ.png",
"imagens/iconPacks/lego/044-american football player.png",
"imagens/iconPacks/lego/045-cheerleader.png",
"imagens/iconPacks/lego/046-santa claus.png",
"imagens/iconPacks/lego/047-diver.png",
"imagens/iconPacks/lego/048-thespian.png",
"imagens/iconPacks/lego/049-man.png",
"imagens/iconPacks/lego/050-man.png",
"imagens/iconPacks/lego/051-cowgirl.png",
"imagens/iconPacks/lego/052-caveman.png",
"imagens/iconPacks/lego/053-witch.png",
"imagens/iconPacks/lego/054-vampire.png",
"imagens/iconPacks/lego/055-queen.png",
"imagens/iconPacks/lego/056-gnome.png",
"imagens/iconPacks/lego/057-injured.png",
"imagens/iconPacks/lego/058-thief.png",
"imagens/iconPacks/lego/059-hiker.png",
"imagens/iconPacks/lego/060-devil.png",
"imagens/iconPacks/lego/061-desert.png",
"imagens/iconPacks/lego/062-ninja.png",
"imagens/iconPacks/lego/063-batman.png",
"imagens/iconPacks/lego/064-superman.png",
"imagens/iconPacks/lego/065-wolverine.png",
"imagens/iconPacks/lego/066-Spiderman.png",
"imagens/iconPacks/lego/067-dummy.png",
"imagens/iconPacks/lego/068-magician.png",
"imagens/iconPacks/lego/069-thor.png",
"imagens/iconPacks/lego/070-deadpool.png",
"imagens/iconPacks/lego/071-businessman.png",
"imagens/iconPacks/lego/072-woman.png",
"imagens/iconPacks/lego/073-mummy.png",
"imagens/iconPacks/lego/074-singer.png",
"imagens/iconPacks/lego/075-Mohawk.png",
"imagens/iconPacks/lego/076-explorer.png",
"imagens/iconPacks/lego/077-dentist.png",
"imagens/iconPacks/lego/078-hip hop.png",
"imagens/iconPacks/lego/079-surgeon.png",
"imagens/iconPacks/lego/080-priest.png"]

let petsPack = ["imagens/iconPacks/pets/001-wild.png",
"imagens/iconPacks/pets/002-snack.png",
"imagens/iconPacks/pets/003-snack-1.png",
"imagens/iconPacks/pets/004-cat.png",
"imagens/iconPacks/pets/005-animal.png",
"imagens/iconPacks/pets/006-pot.png",
"imagens/iconPacks/pets/007-animals.png",
"imagens/iconPacks/pets/008-animals-1.png",
"imagens/iconPacks/pets/009-play.png",
"imagens/iconPacks/pets/010-animals-2.png",
"imagens/iconPacks/pets/011-pet.png",
"imagens/iconPacks/pets/012-cat-1.png",
"imagens/iconPacks/pets/013-canned-food.png",
"imagens/iconPacks/pets/014-animal-1.png",
"imagens/iconPacks/pets/015-animals-3.png",
"imagens/iconPacks/pets/016-entertainment.png",
"imagens/iconPacks/pets/017-organic.png",
"imagens/iconPacks/pets/018-building.png",
"imagens/iconPacks/pets/019-app.png"]

let pokemonPack = ["imagens/iconPacks/pokemon/abra.png",
"imagens/iconPacks/pokemon/action-1.png",
"imagens/iconPacks/pokemon/action.png",
"imagens/iconPacks/pokemon/augmented-reality-1.png",
"imagens/iconPacks/pokemon/augmented-reality.png",
"imagens/iconPacks/pokemon/backpack.png",
"imagens/iconPacks/pokemon/battle.png",
"imagens/iconPacks/pokemon/bellsprout.png",
"imagens/iconPacks/pokemon/blue-team.png",
"imagens/iconPacks/pokemon/bracelet.png",
"imagens/iconPacks/pokemon/bullbasaur.png",
"imagens/iconPacks/pokemon/camera.png",
"imagens/iconPacks/pokemon/candy.png",
"imagens/iconPacks/pokemon/caterpie.png",
"imagens/iconPacks/pokemon/charmander.png",
"imagens/iconPacks/pokemon/clock.png",
"imagens/iconPacks/pokemon/combat-power.png",
"imagens/iconPacks/pokemon/compass.png",
"imagens/iconPacks/pokemon/crown.png",
"imagens/iconPacks/pokemon/dratini.png",
"imagens/iconPacks/pokemon/eevee.png",
"imagens/iconPacks/pokemon/egg-1.png",
"imagens/iconPacks/pokemon/egg-incubator-1.png",
"imagens/iconPacks/pokemon/egg-incubator.png",
"imagens/iconPacks/pokemon/egg.png",
"imagens/iconPacks/pokemon/fight.png",
"imagens/iconPacks/pokemon/fist.png",
"imagens/iconPacks/pokemon/footprints.png",
"imagens/iconPacks/pokemon/gear.png",
"imagens/iconPacks/pokemon/gotcha.png",
"imagens/iconPacks/pokemon/heart.png",
"imagens/iconPacks/pokemon/hyper-potion.png",
"imagens/iconPacks/pokemon/incense-score.png",
"imagens/iconPacks/pokemon/incense.png",
"imagens/iconPacks/pokemon/incenses.png",
"imagens/iconPacks/pokemon/insignia-1.png",
"imagens/iconPacks/pokemon/insignia.png",
"imagens/iconPacks/pokemon/instinct-1.png",
"imagens/iconPacks/pokemon/instinct.png",
"imagens/iconPacks/pokemon/jigglypuff.png",
"imagens/iconPacks/pokemon/lucky-egg-score.png",
"imagens/iconPacks/pokemon/lucky-egg.png",
"imagens/iconPacks/pokemon/lucky-eggs.png",
"imagens/iconPacks/pokemon/lure-module-1.png",
"imagens/iconPacks/pokemon/lure-module-score.png",
"imagens/iconPacks/pokemon/lure-module.png",
"imagens/iconPacks/pokemon/mankey.png",
"imagens/iconPacks/pokemon/map.png",
"imagens/iconPacks/pokemon/mega-ball.png",
"imagens/iconPacks/pokemon/meowth.png",
"imagens/iconPacks/pokemon/mew.png",
"imagens/iconPacks/pokemon/money-bag.png",
"imagens/iconPacks/pokemon/mystic-1.png",
"imagens/iconPacks/pokemon/mystic.png",
"imagens/iconPacks/pokemon/new.png",
"imagens/iconPacks/pokemon/open-pokeball.png",
"imagens/iconPacks/pokemon/pawprints.png",
"imagens/iconPacks/pokemon/pidgey.png",
"imagens/iconPacks/pokemon/pikachu-1.png",
"imagens/iconPacks/pokemon/pikachu-2.png",
"imagens/iconPacks/pokemon/pikachu.png",
"imagens/iconPacks/pokemon/player-1.png",
"imagens/iconPacks/pokemon/player.png",
"imagens/iconPacks/pokemon/pointer.png",
"imagens/iconPacks/pokemon/pokebag.png",
"imagens/iconPacks/pokemon/pokeball.png",
"imagens/iconPacks/pokemon/pokeballs.png",
"imagens/iconPacks/pokemon/pokecoin.png",
"imagens/iconPacks/pokemon/pokecoins-1.png",
"imagens/iconPacks/pokemon/pokecoins.png",
"imagens/iconPacks/pokemon/pokedex.png",
"imagens/iconPacks/pokemon/pokestop-1.png",
"imagens/iconPacks/pokemon/pokestop-2.png",
"imagens/iconPacks/pokemon/pokestop-3.png",
"imagens/iconPacks/pokemon/pokestop.png",
"imagens/iconPacks/pokemon/potion.png",
"imagens/iconPacks/pokemon/psyduck.png",
"imagens/iconPacks/pokemon/rattata.png",
"imagens/iconPacks/pokemon/razz-berry.png",
"imagens/iconPacks/pokemon/red-team.png",
"imagens/iconPacks/pokemon/revive.png",
"imagens/iconPacks/pokemon/scene.png",
"imagens/iconPacks/pokemon/smartphone.png",
"imagens/iconPacks/pokemon/snorlax.png",
"imagens/iconPacks/pokemon/squirtle.png",
"imagens/iconPacks/pokemon/star-1.png",
"imagens/iconPacks/pokemon/star.png",
"imagens/iconPacks/pokemon/stardust.png",
"imagens/iconPacks/pokemon/super-potion.png",
"imagens/iconPacks/pokemon/superball.png",
"imagens/iconPacks/pokemon/tornado-1.png",
"imagens/iconPacks/pokemon/tornado.png",
"imagens/iconPacks/pokemon/ultra-ball.png",
"imagens/iconPacks/pokemon/up-arrow.png",
"imagens/iconPacks/pokemon/valor-1.png",
"imagens/iconPacks/pokemon/valor.png",
"imagens/iconPacks/pokemon/venonat.png",
"imagens/iconPacks/pokemon/weedle.png",
"imagens/iconPacks/pokemon/yellow-team.png",
"imagens/iconPacks/pokemon/zubat.png"]

let radioactivePack = ["imagens/iconPacks/radioactive/002-industry.png",
"imagens/iconPacks/radioactive/003-power-1.png",
"imagens/iconPacks/radioactive/004-power-2.png",
"imagens/iconPacks/radioactive/005-ecology-and-environment.png",
"imagens/iconPacks/radioactive/006-eco.png",
"imagens/iconPacks/radioactive/007-controls.png",
"imagens/iconPacks/radioactive/008-world.png",
"imagens/iconPacks/radioactive/009-education.png",
"imagens/iconPacks/radioactive/010-cloud.png",
"imagens/iconPacks/radioactive/011-deoxyribonucleic-acid.png",
"imagens/iconPacks/radioactive/012-light.png",
"imagens/iconPacks/radioactive/013-food.png",
"imagens/iconPacks/radioactive/014-transport.png",
"imagens/iconPacks/radioactive/015-power-3.png",
"imagens/iconPacks/radioactive/016-technology.png",
"imagens/iconPacks/radioactive/017-station.png",
"imagens/iconPacks/radioactive/018-power-4.png",
"imagens/iconPacks/radioactive/019-direction.png",
"imagens/iconPacks/radioactive/020-power.png",
"imagens/iconPacks/radioactive/weather.png"]

let socialMediaPack = ["imagens/iconPacks/socialMedia/001-youtube.png",
"imagens/iconPacks/socialMedia/002-yelp.png",
"imagens/iconPacks/socialMedia/003-wordpress.png",
"imagens/iconPacks/socialMedia/004-wikipedia.png",
"imagens/iconPacks/socialMedia/005-whatsapp.png",
"imagens/iconPacks/socialMedia/006-vine.png",
"imagens/iconPacks/socialMedia/007-vimeo.png",
"imagens/iconPacks/socialMedia/008-twitter.png",
"imagens/iconPacks/socialMedia/009-tumblr.png",
"imagens/iconPacks/socialMedia/010-trello.png",
"imagens/iconPacks/socialMedia/011-stumbleupon.png",
"imagens/iconPacks/socialMedia/012-spotify.png",
"imagens/iconPacks/socialMedia/013-soundcloud.png",
"imagens/iconPacks/socialMedia/014-snapchat.png",
"imagens/iconPacks/socialMedia/015-skype.png",
"imagens/iconPacks/socialMedia/016-shutterstock.png",
"imagens/iconPacks/socialMedia/017-scribd.png",
"imagens/iconPacks/socialMedia/018-reddit.png",
"imagens/iconPacks/socialMedia/019-quora.png",
"imagens/iconPacks/socialMedia/020-plaxo.png",
"imagens/iconPacks/socialMedia/021-pinterest.png",
"imagens/iconPacks/socialMedia/022-periscope.png",
"imagens/iconPacks/socialMedia/023-paypal.png",
"imagens/iconPacks/socialMedia/024-path.png",
"imagens/iconPacks/socialMedia/025-myspace.png",
"imagens/iconPacks/socialMedia/026-medium.png",
"imagens/iconPacks/socialMedia/027-linkedin.png",
"imagens/iconPacks/socialMedia/028-kickstarter.png",
"imagens/iconPacks/socialMedia/029-instagram.png",
"imagens/iconPacks/socialMedia/030-html-5.png",
"imagens/iconPacks/socialMedia/031-howcast.png",
"imagens/iconPacks/socialMedia/032-hi5.png",
"imagens/iconPacks/socialMedia/033-google-plus.png",
"imagens/iconPacks/socialMedia/034-foursquare.png",
"imagens/iconPacks/socialMedia/035-flickr.png",
"imagens/iconPacks/socialMedia/036-facebook.png",
"imagens/iconPacks/socialMedia/037-etsy.png",
"imagens/iconPacks/socialMedia/038-envato.png",
"imagens/iconPacks/socialMedia/039-dropbox.png",
"imagens/iconPacks/socialMedia/040-dribbble.png",
"imagens/iconPacks/socialMedia/041-deviantart.png",
"imagens/iconPacks/socialMedia/042-delicious.png",
"imagens/iconPacks/socialMedia/043-creative-market.png",
"imagens/iconPacks/socialMedia/044-buffer.png",
"imagens/iconPacks/socialMedia/045-box.png",
"imagens/iconPacks/socialMedia/046-bing.png",
"imagens/iconPacks/socialMedia/047-behance.png",
"imagens/iconPacks/socialMedia/049-amazon.png"]

let sustainableEnergyPack = ["imagens/iconPacks/sustainableEnergy/001-nature.png",
"imagens/iconPacks/sustainableEnergy/002-power.png",
"imagens/iconPacks/sustainableEnergy/003-tree.png",
"imagens/iconPacks/sustainableEnergy/004-earth.png",
"imagens/iconPacks/sustainableEnergy/005-arrows.png",
"imagens/iconPacks/sustainableEnergy/006-construction.png",
"imagens/iconPacks/sustainableEnergy/007-power-1.png",
"imagens/iconPacks/sustainableEnergy/008-arrows-1.png",
"imagens/iconPacks/sustainableEnergy/009-signs.png",
"imagens/iconPacks/sustainableEnergy/010-industry.png",
"imagens/iconPacks/sustainableEnergy/011-ecological.png",
"imagens/iconPacks/sustainableEnergy/012-weather.png",
"imagens/iconPacks/sustainableEnergy/013-power-2.png",
"imagens/iconPacks/sustainableEnergy/014-earth-1.png",
"imagens/iconPacks/sustainableEnergy/015-ecology.png",
"imagens/iconPacks/sustainableEnergy/016-industry-1.png",
"imagens/iconPacks/sustainableEnergy/017-arrows-2.png",
"imagens/iconPacks/sustainableEnergy/018-tower.png",
"imagens/iconPacks/sustainableEnergy/019-sky.png",
"imagens/iconPacks/sustainableEnergy/020-technology.png"]

// Define backs, avatars e packs caso estes não existam na localStorage (como por exemplo, na primeira interação)

if (!(localStorage.getItem("backs"))) {
    let backs = {
    default: "imagens/cardBacks/cardBack.png",
    halloween: "imagens/cardBacks/halloweenCardBack.png",
    illusion: "imagens/cardBacks/illusionCardBack.png",
    superMario: "imagens/cardBacks/marioCardBack.png",
    space: "imagens/cardBacks/spaceCardBack.png"
    }
    localStorage.setItem("backs", JSON.stringify(backs))

}

if (!(localStorage.getItem("avatars"))) {
    let avatars = {
        doge: "imagens/avatares/dogeAvatar.png",
        googleDinossaur: "imagens/avatares/googleDinossaur.png",
        nerdLady: "imagens/avatares/nerdLadyAvatar.png",
        snake: "imagens/avatares/snakeAvatar.png",
        starWars: "imagens/avatares/starWarsAvatar.png",
        theCardMaster: "imagens/avatares/theCardGuyAvatar.png",
        speedRunner: "imagens/avatares/theSpeedRunnerAvatar.png",
        theWay: "imagens/avatares/theWayAvatar.png"
    }
    localStorage.setItem("avatars", JSON.stringify(avatars))
}

if (!(localStorage.getItem("packs"))) {

    let packs = {
        default: defaultPack,
        pets: petsPack,
        pokemon: pokemonPack,
        desert: desertPack,
        emoji: emojiPack,
        epidemic: epidemicPack,
        food: foodPack,
        lego: legoPack,
        radioactive: radioactivePack,
        socialMedia: socialMediaPack,
        sustainableEnergy: sustainableEnergyPack}
        
    localStorage.setItem("packs", JSON.stringify(packs))
}
